---
# handlers file for roles/nginx
- name: restart nginx docker
  docker_container:
    name: "{{ docker_name }}"
#    hostname: "{{ docker_name }}"
#    ports:
#      "{{ docker_nginx_port }}:80"
#    volumes:
#      "{{ docker_volume }}:/etc/nginx/"
#    image: nginx:alpine
    state: started
    restart: yes
- pause:
    prompt: "Waiting 20 seconds for restarting nginx docker container"
    seconds: 20
